import { BookDetails } from 'src/app/models/book-detail';

export const BOOKDETAILS: BookDetails[] = [
  {
    id: 1,
    name: 'The Song of Archilles',
    author: 'Madeline Miller',
    purchase: true,
    price: 200,
    bookImg: 'book1.jpg',
    availibilty: 0,
  },
  {
    id: 2,
    name: 'Dont let Him Know',
    author: 'Sandip Roy',
    purchase: true,
    price: 250,
    bookImg: 'book2.jpg',
    availibilty: 0,
  },
  {
    id: 3,
    name: 'The Priory',
    author: 'Tomasz Jedrowksi',
    purchase: true,
    price: 290,
    bookImg: 'book3.jpg',
    availibilty: 0,
  },
  {
    id: 4,
    name: 'Maggie & Me',
    author: 'Damian Barr',
    purchase: true,
    price: 300,
    bookImg: 'book6.jpg',
    availibilty: 0,
  },
  // {
  //   id: 5,
  //   name: 'Story we never tell',
  //   author: 'Savi Sharma',
  //   purchase: false,
  //   price: 190,
  //   bookImg: 'book4.jpg',
  //   availibilty: 3,
  // },
  // {
  //   id: 6,
  //   name: 'Let Me Say It Now',
  //   author: 'Rakesh Maria',
  //   purchase: true,
  //   price: 640,
  //   bookImg: 'book5.jpg',
  //   availibilty: 4,
  // },
];
